# This is a config for E2B sandbox template.
# You can use template ID (6jyrzyup32dhmmtcusy5) or template name (flowcommander-node22) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("flowcommander-node22") # Sync sandbox
# sandbox = await AsyncSandbox.create("flowcommander-node22") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('flowcommander-node22')

team_id = "dc5252c5-489f-4b28-9131-2da8cf3c9253"
dockerfile = "e2b.Dockerfile"
template_name = "flowcommander-node22"
template_id = "6jyrzyup32dhmmtcusy5"
